language: cpp
  
compiler:
    - clang
    - gcc
  
before_script:
  choco upgrade cmake
  
addons:
   apt:
   sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
 
 install:
    # скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh
    
script: 
- cmake .
-cmake --build .

