language: cpp

before_script:
  choco upgrade cmake

compiler:
    - clang
    - gcc
    
addons:
   apt:
    packages:
      - cmake-data
      - cmake
      
script: 
- cmake .
- cmake --build . -- -j2
