language: cpp

compiler:
    - clang
    - gcc

matrix:
include:
- os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
matrix:       
include:
 - os: osx
   osx_image: xcode8
   env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

 
env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
   
before_install:
    - eval "${MATRIX_EVAL}"
    
script: 
- cmake --version
- cmake CMakeLists.txt
- cmake --build . -- -j2
