language: cpp


  
compiler:
    - clang
    - gcc
    
addons:
   apt:
    packages:
      - cmake-data
      - cmake
      
script: 
- mkdir build
- cd build
- cmake ..
cmake --build .

