language: cpp


  
compiler:
    - clang
    - gcc
    
addons:
   apt:
    packages:
      - cmake-data
      - cmake
 
 install:
    # скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh
    
script: 
- mkdir build
- cd build
- cmake ..
-cmake --build .

