language: cpp



compiler:
    - clang
    - gcc
   

addons:
apt:
  sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
 snaps:
       - name: cmake
         confinement: classic
         #channel: latest/candidate
         channel: 3.20/candidate
         #channel: 3.17/beta
 
env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
    
script: 
- cmake --version
- cmake CMakeLists.txt
- cmake --build . -- -j2
