language: cpp



compiler:
    - clang
    - gcc
   

    addons:
     snaps:
       - name: cmake
         confinement: classic
         #channel: latest/candidate
         channel: 3.18/candidate
         #channel: 3.17/beta
      
script: 
- cmake .
- cmake --build . -- -j2
