language: cpp

before_script:
  choco upgrade cmake 3.20.0

compiler:
    - clang
    - gcc
   
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo apt-get update -q;
    CMAKE_VERSION=3.20.0;
    CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz";
    echo CMAKE_URL=${CMAKE_URL};
    mkdir cmake-${CMAKE_VERSION} && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-${CMAKE_VERSION};
    export PATH=${PWD}/cmake-${CMAKE_VERSION}/bin:${PATH};
    cmake --version;
  else
    cmake --version;
  fi
  
addons:
   apt:
    packages:
      - cmake-data
      - cmake
      
script: 
- cmake .
- cmake --build . -- -j2
