language: cpp



compiler:
    - clang
    - gcc
   

addons:
apt:
sources:
      - ubuntu-toolchain-r-tes
packages:
      - gcc-6
      - g++-6
      - cmake  
snaps:
       - name: cmake
         confinement: classic
         #channel: latest/candidate
         channel: 3.20/candidate
         #channel: 3.17/beta
      
script:

 
- cmake --version
- cmake CMakeLists.txt
- cmake --build . -- -j2