language: cpp



compiler:
    - clang
    - gcc
   

addons:
apt:
    packages:
      - g++-7
 snaps:
       - name: cmake
         confinement: classic
         #channel: latest/candidate
         channel: 3.20/candidate
         #channel: 3.17/beta
      
script: 
 - export CC=gcc-7
 - export CXX=g++-7
- cmake --version
- cmake CMakeLists.txt
- cmake --build . -- -j2
