language: cpp



compiler:
    - clang
    - gcc
   
addons:
    snaps:
      - name:cmake
      confinement: classic
      channel: latest/candidate
      
script: 
- cmake .
- cmake --build . -- -j2
