language: cpp

before_install:
  - chmod +x build.sh
  
compiler:
    - clang
    - gcc
    
addons:
   apt:
    packages:
      - cmake-data
      - cmake
      
script: 
- cmake .
- cmake --build . -- -j2

